name: ExpGrowth
favicon: null
layout_spectrum: 0.49536482780240476
typography_spectrum: 0.8858066778630018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.42040108679793775
  lightness: 0.12295007007196546
  saturation: 0.6010011595208198
  rhythmicContrast: 0.06935793184675276
purpose: []
